-- ============================================================
-- CO-THINK BIGGER / migration v3 : AI アシスト基盤
--   Supabase の SQL Editor で全文を実行してください（冪等）。
--   ※ migration_v2_collaboration.sql の後に実行すること
-- ============================================================

-- ------------------------------------------------------------
-- 1. ユーザーごとの AI 接続情報
--
--    API キーは AES-256-GCM で暗号化して保存する（平文では持たない）。
--    復号鍵はサーバー側の環境変数 AI_CREDENTIAL_SECRET のみが持つ。
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "AiCredential" (
  "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "profileId"    UUID NOT NULL,
  "provider"     TEXT NOT NULL,           -- 'anthropic' | 'openai' | 'gemini'
  "encryptedKey" TEXT NOT NULL,
  "model"        TEXT,
  "createdAt"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "AiCredential_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "AiCredential_profileId_fkey"
    FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "AiCredential_profileId_provider_key"
  ON "AiCredential"("profileId", "provider");

-- どのプロバイダを使うかの選択
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "aiProvider" TEXT;

-- ------------------------------------------------------------
-- 2. AiCredential だけは必ず RLS で保護する
--
--    このプロジェクトは現状ほぼ全テーブルが匿名キーで読める状態だが、
--    API キーは他人に見えては絶対にいけないので、
--    ここだけは「本人の行しか触れない」ポリシーを必ず張る。
-- ------------------------------------------------------------
ALTER TABLE "AiCredential" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "own_ai_credential" ON "AiCredential";
CREATE POLICY "own_ai_credential" ON "AiCredential"
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM "Profile" p
       WHERE p."id" = "AiCredential"."profileId"
         AND p."userId" = auth.uid()::text
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM "Profile" p
       WHERE p."id" = "AiCredential"."profileId"
         AND p."userId" = auth.uid()::text
    )
  );

-- ------------------------------------------------------------
-- 3. AI との壁打ちログ（ステップ単位で残す）
--
--    「前回どこまで考えたか」が残らないと、日をまたいだ再開ができない。
--    チームにも見えるようにして、非同期でも思考過程を共有できるようにする。
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "CoachMessage" (
  "id"        BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "projectId" BIGINT NOT NULL,
  "profileId" UUID NOT NULL,
  "step"      TEXT NOT NULL,
  "role"      TEXT NOT NULL,             -- 'user' | 'assistant'
  "content"   TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CoachMessage_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "CoachMessage_projectId_fkey"
    FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE,
  CONSTRAINT "CoachMessage_profileId_fkey"
    FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "CoachMessage_thread_idx"
  ON "CoachMessage"("projectId", "profileId", "step", "createdAt");

-- ------------------------------------------------------------
-- 4. 毎日の習慣づけ用: 活動ログ
--
--    連続日数（ストリーク）と「今日やったこと」を出すために、
--    各テーブルの createdAt を毎回集計するのは重い。
--    1 日 1 行に丸めた軽いログを別に持つ。
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "ActivityDay" (
  "id"        BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "profileId" UUID NOT NULL,
  "day"       DATE NOT NULL,
  "count"     INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT "ActivityDay_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "ActivityDay_profileId_fkey"
    FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "ActivityDay_profileId_day_key"
  ON "ActivityDay"("profileId", "day");

-- 1 日分の活動を積む（同じ日なら count を増やすだけ）
CREATE OR REPLACE FUNCTION bump_activity(p_profile UUID)
RETURNS void AS $$
BEGIN
  INSERT INTO "ActivityDay"("profileId", "day", "count")
  VALUES (p_profile, (now() AT TIME ZONE 'Asia/Tokyo')::date, 1)
  ON CONFLICT ("profileId", "day")
  DO UPDATE SET "count" = "ActivityDay"."count" + 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ------------------------------------------------------------
-- 5. リアルタイム配信に新テーブルを追加
-- ------------------------------------------------------------
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['CoachMessage'] LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables
       WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = t
    ) THEN
      EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', t);
    END IF;
  END LOOP;
END $$;
