-- 1. Profileテーブル以外のIDをbigint (IDENTITY)に変更するためのalter script
-- ProfileはUUIDのまま

-- 参照制約（Foreign Key）があるため、依存関係の順序に注意して変更するか、CASCADEを利用する必要があります。
-- ただし、カラムの型変更（String -> BigInt）はデータが入っているとキャストエラーになる可能性があります。
-- 現在データはすべてテストデータで消しても問題ない前提であれば、TRUNCATE/DROPしてから作り直すのが安全です。
-- ここでは、既存テーブルを再定義するSQLを作成します。

-- 既存テーブルの削除（依存関係順）
DROP TABLE IF EXISTS "Achievement";
DROP TABLE IF EXISTS "Notification";
DROP TABLE IF EXISTS "Message";
DROP TABLE IF EXISTS "Evaluation";
DROP TABLE IF EXISTS "Solution";
DROP TABLE IF EXISTS "Desire";
DROP TABLE IF EXISTS "Choice";
DROP TABLE IF EXISTS "SubProblem";
DROP TABLE IF EXISTS "Reaction";
DROP TABLE IF EXISTS "Candidate";
DROP TABLE IF EXISTS "ProjectMember";
DROP TABLE IF EXISTS "Project";
DROP TABLE IF EXISTS "Profile"; -- Profileも作り直しますが、定義はUUID維持

-- テーブル再作成

-- Profile (UUID)
CREATE TABLE "Profile" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "userId" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "avatarUrl" TEXT,
    "jobTitle" TEXT,
    "bio" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Profile_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Profile_userId_key" ON "Profile"("userId");
CREATE UNIQUE INDEX "Profile_username_key" ON "Profile"("username");

-- Project (BigInt)
CREATE TABLE "Project" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "inviteCode" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Project_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Project_inviteCode_key" ON "Project"("inviteCode");

-- ProjectMember (BigInt ID)
CREATE TABLE "ProjectMember" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "projectId" BIGINT NOT NULL,
    "profileId" UUID NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'member',

    CONSTRAINT "ProjectMember_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "ProjectMember_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ProjectMember_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "ProjectMember_projectId_profileId_key" ON "ProjectMember"("projectId", "profileId");

-- Candidate (BigInt ID)
CREATE TABLE "Candidate" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "projectId" BIGINT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "authorId" TEXT NOT NULL, -- User ID (String from Supabase Auth)
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Candidate_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Candidate_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Reaction (BigInt ID)
CREATE TABLE "Reaction" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "candidateId" BIGINT NOT NULL,
    "profileId" UUID NOT NULL,
    "emoji" TEXT NOT NULL,
    CONSTRAINT "Reaction_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Reaction_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Reaction_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "Reaction_candidateId_profileId_emoji_key" ON "Reaction"("candidateId", "profileId", "emoji");

-- SubProblem (BigInt ID)
CREATE TABLE "SubProblem" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "projectId" BIGINT NOT NULL,
    "title" TEXT NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "SubProblem_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "SubProblem_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Choice (BigInt ID)
CREATE TABLE "Choice" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "subProblemId" BIGINT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "sourceURL" TEXT,
    "isOutsideDomain" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Choice_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Choice_subProblemId_fkey" FOREIGN KEY ("subProblemId") REFERENCES "SubProblem"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Desire (BigInt ID)
CREATE TABLE "Desire" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "projectId" BIGINT NOT NULL,
    "type" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Desire_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Desire_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Solution (BigInt ID)
CREATE TABLE "Solution" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "projectId" BIGINT NOT NULL,
    "name" TEXT,
    "components" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Solution_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Solution_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Evaluation (BigInt ID)
CREATE TABLE "Evaluation" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "solutionId" BIGINT NOT NULL,
    "desireId" BIGINT NOT NULL,
    "score" INTEGER NOT NULL,
    CONSTRAINT "Evaluation_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Evaluation_solutionId_fkey" FOREIGN KEY ("solutionId") REFERENCES "Solution"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Evaluation_desireId_fkey" FOREIGN KEY ("desireId") REFERENCES "Desire"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "Evaluation_solutionId_desireId_key" ON "Evaluation"("solutionId", "desireId");

-- Message (BigInt ID)
CREATE TABLE "Message" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "content" TEXT NOT NULL,
    "projectId" BIGINT,
    "candidateId" BIGINT,
    "profileId" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Message_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Message_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Message_candidateId_fkey" FOREIGN KEY ("candidateId") REFERENCES "Candidate"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Message_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Notification (BigInt ID)
CREATE TABLE "Notification" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "profileId" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "read" BOOLEAN NOT NULL DEFAULT false,
    "type" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Notification_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Achievement (BigInt ID)
CREATE TABLE "Achievement" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "profileId" UUID NOT NULL,
    "badgeType" TEXT NOT NULL,
    "unlockedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Achievement_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Achievement_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
